### ISSUE TITLE
Optimization for opportunistic charging

### ISSUE THREAD

**Issue by janneho** [jonasbkarlsson/ev_smart_charging#114]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Have option to trigger opportunistic charging when tomorrows price is lower than this night, even if price for this night is under price limit. Picture attached for this night. Something that would trigger opportunistic charging when price for last hour of tomorrow is cheaper than it would be tonight (maybe even another slider so that if tomorrows price is 0-200% from the price it would cost tonight to charge after minium SOC has been reached).

**Describe alternatives you've considered**
N/A

**Additional context**
Thanks for integration, it has been working great!

Here is charging schedule for tonight. Price tonight is under price limit and opportunistic level limit. It clearly still would be chaper to charge to minium SOC (in picture current EV SOC>minium EV SOC), and charge to full next night. Prices vary so much from night to night, that it is hard to have fixed monetary limit. It would be easy to set percent limit that controls opportunistic charging (for example 110% from tonights price).

![kuva](https://user-images.githubusercontent.com/2905409/214845789-da04061b-4819-4521-955c-c0c6d5b31b42.png)

**Comment by jonasbkarlsson** [comment]
Thanks for the feedback and the question.

I would guess that you have set `select.ev_smart_charging_charge_completion_time` to some certain time. If so, then what you see is the expected charging schedule. In order to achieve what you ask for, you would need to set `select.ev_smart_charging_charge_completion_time` to `None`.

**Comment by jonasbkarlsson** [comment]
Thanks for the feedback and the question.

What is the SOC of the car? If it's below 60% (below the Minium EV SOC), then that could explain what you see.

**Comment by janneho** [comment]
It is 69% now.

**Comment by jonasbkarlsson** [comment]
If you check the attributes of the main sensor entity, what is `Charging is planned` set to?

**Comment by janneho** [comment]
Charging is planned: true

**Comment by jonasbkarlsson** [comment]
Hmm. Weird. Can you paste all the attributes here?
And what `Target SOC` and `number.ev_smart_charging_charging_speed` do you have?

**Comment by jonasbkarlsson** [comment]
Thanks. I will look into this more. 

By the way, did this happen directly after restarting Home Assistant?

If you click on "Smart charging activated" twice (to turn it off and then on again), the charging schedule should be recalculated, and maybe that will give you a correct charging schedule.

**Comment by janneho** [comment]
Maybe i explained this badly.

it recalculates it ok. It changes when i change price limit etc.
If i understand opportunistic mode right, this is how it should work now? It is scheduled 1 hour at 0.00, That is cheapest hour before 7.00 (completion.time).
Also at 0.00 price is 6,72cent < 12cent*0,6 (Price limit * Opportunistic level).

What i am suggesting that there is new/alternative mechanism for opportunistic charging that works something like this
![temp](https://user-images.githubusercontent.com/2905409/214938031-1d0f2646-0897-4073-998c-f08990ca6b71.png)
When price at A is higher than at B * settable percent, only charge to minimum SOC and do not care at all what price limit is set at. Here A is first cheapest hour AFTER minimum SOC has been reached.

**Comment by jonasbkarlsson** [comment]
I understand what you mean. What you ask for is how it should work. If opportunistic charging is enabled, there shouldn't be any chargingen at A. And since you have set the completion time to 07:00m then there should not be any charging at B either now. The charging at B shoulfd appear after noon tomorrow, after the prices for the day after tomorrow is available.

So if you have had opportunistic charging enabled and the integration has scheduled charging at A, then there is something wrong.

**Comment by janneho** [comment]
Ok. i did not understand opportunistic charging right then. Now it just seems to lower price limit to Electricity price limit * Opportunistic level / 100 when I have opportunistic charging on.

I understand that there should not be any scheduled charging at B, Price at B should still used as Electricity price limit?

**Comment by jonasbkarlsson** [comment]
Sorry. Now I looked again. I did missunderstood you.

There is no bug in the code. It is working as intended.

My intention was that if the last hour tomorrow has a price less than `Electricity price limit * Opportunistic level / 100` then the price limit will be lowered to `Electricity price limit * Opportunistic level / 100`.

I think what you ask for could be expressed as in addition to lower the price limit, the `select.ev_smart_charging_charge_completion_time` should be ignored.

**Comment by jonasbkarlsson** [comment]
So then it will become like this instead:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/12384363/214960428-d8bf04c0-6eb1-446c-b2c2-e2bf15ea1bdd.png">

**Comment by janneho** [comment]
Kinda yes. but also no. 

If select.ev_smart_charging_charge_completion_time is set, it must always be scheduled to meet minium ev soc limit to be charged before that.
If price for last hours next day (black bar in your drawing) is lower than lowest price before select.ev_smart_charging_charge_completion_time (after reaching minimum soc level), then stop charging for this session. No need to calculate any electricity price limit/opportunistic level, becouse it is 100% sure that next night is cheaper in any case (atleast for first hour or so).

**Comment by jonasbkarlsson** [comment]
Yes, agree. And then it becomes much more complicated than I first thought. The integration is now started to reach the limit on how complicated rules the current design can handle. I need to think if this can be achieve with a reasonable effort.

Note that another way to look at this is that you could have set `number.ev_smart_charging_opportunistic_level` to a lower value if you wanted to be more agressive in the opportunistic savings. If it had been set to 50%, you wouldn't had get any scheduled charging this night.

**Comment by janneho** [comment]
What if last hour of tomorrow * opportunistic level (50%-150%) is used as Electricity price limit?

I would like to have some kind of set and forget, that is why this automation is so good.
But when electricity price range from 0,5cent to 50cent/kwh in one month, it is impossible to set any limits to price that would work. 
We all know that if last hour of tomorrow is lower than tonight, it is less than likely cheaper to postpone charging. That is not fixed as electricity price limit is.

**Comment by jonasbkarlsson** [comment]
Thanks for that suggestion. That would be easy to implement. Let me think about that.

It is my intention to make it "set and forget".

**Comment by jonasbkarlsson** [comment]
The intention of the current `switch.ev_smart_charging_apply_price_limit` is to avoid charging at home if the electrity price is high compared to other ways of charging, such as public charging or charging at you work place.

And then `switch.ev_smart_charging_opportunistic_charging` was added to make it possible to optimize the cost a little more.

Now, with the suggestion "last hour of tomorrow * opportunistic level (50%-150%) is used as Electricity price limit", the orignal fixed price set by `switch.ev_smart_charging_apply_price_limit` is not used at all, right?

So my observation is that this suggestion is not an improvement of the current `switch.ev_smart_charging_apply_price_limit` and `switch.ev_smart_charging_opportunistic_charging`, but a suggestion to have a different strategy to limit charging. And this strategy does not have an upper limit on the electricity price, meaning that charging will happen even if the price might be very high.

Would you agree on that? And is that what you really want? I don't think that was in your original request.

**Comment by janneho** [comment]
That would be ok for me. Charging to min soc for whatever price should be done anyways. 

Is it possible to leave price limit as it is, and have option to turn this new limit on? When using price limit, we have allready ok with the possibility that charging stops on minium soc level.

Then i ihink that logick could be somethinh like rhis.
If (price to charge over minimum soc) > (price limit OR last price next day) --> only charge to minimum soc.

**Comment by oveand** [comment]
Sorry for interfering but was trying out the opportunistic charging feature and didn't really understand how this was calculated, was first looking into the code/PR, which lead me to this issue.

I just want to quickly describe my take on this challenge. Every day I compute a custom price limit as an average of the price at 23:00 today and the price at 23:00 tomorrow, i.e., if today's price at 23:00 is DKK 1.50 and tomorrows price at 23:00 is DKK 1.10 then I will set a custom price limit of DKK 1.30. This has been working out quite well for a month and will keep postpone charging "until tomorrow" if the price is continuously dropping. Of cause minimum SoC is still obeyed as long as the original price limit is the max.
An opportunistic level could of cause balance how strict towards highest vs lowest "23:00" price one wants to set the custom limit, though for me an average price has worked out quite well.

Just my 2 cents..

**Comment by janneho** [comment]
That is about same as i am doing (except we got prices always to 1;00 morning).

So if instead just using fixed price limit, could we use last price (1:00 here) as limit if it is lower than fixed price limit? And maybe settable percent on top of last price.

So when price limit is 10cent, and last price tomorrow is 11 cent, limit would be 10 as it is now. If last price tomorrow is 9 cent, use that as price limit instead of 10 cent. I have used tomorrows last price-10%, but i thik average could also work as well if not even better.

**Comment by oveand** [comment]
@janneho Yes this does indeed sound quite like the same approach, defining a variable max price limit to either prioritize charging this night, if price seems lower, or postpone until tomorrow if we estimate prices will drop lower then.
I started out using lowest price of tonight 23 vs tomorrow at 23 (last avaliable hour in DK) but sometimes prices doesn't drop any further during the night and only few hours were able to charge due to limit. I guess the usual price variations may vary between countries?

**Comment by janneho** [comment]
It really is somewhat guessing for tomorrows price but it works quite well and do not charge if tomorrows price is lower.

I have made quick dumb hacky automation, that somewhat works... It just calculates limits at 15:00 (we get new prices at 14:00) Everything is hard coded, 10 cent is max price limit.

```alias: Set EV charging price limit
description: Calculate limit from nordpool
trigger:
  - platform: time
    at: "15:00:00"
condition: []
action:
  - if:
      - condition: template
        value_template: >-
          {{ (((state_attr('sensor.nordpool_kwh_fi_eur_3_10_01', 'today')[23]) +
          (state_attr('sensor.nordpool_kwh_fi_eur_3_10_01', 'tomorrow')[23])) /
          2) < 10}}
    then:
      - service: number.set_value
        data:
          value: >-
            {{ ((state_attr('sensor.nordpool_kwh_fi_eur_3_10_01', 'today')[23])
            + (state_attr('sensor.nordpool_kwh_fi_eur_3_10_01',
            'tomorrow')[23])) /2}}
        target:
          entity_id: number.ev_smart_charging_electricity_price_limit
    else:
      - service: number.set_value
        data:
          value: "10"
        target:
          entity_id: number.ev_smart_charging_electricity_price_limit
mode: single
```

**Comment by oveand** [comment]
Lol, almost a 1:1 copy of my automation, except I use energi data service 😁

**Comment by oveand** [comment]
![fun_power](https://user-images.githubusercontent.com/13885942/221399811-33b5e400-67d2-44fb-a3cf-d472cfcdf7a4.png)
Though some times this rule of thumb just does not apply :)

**Comment by janneho** [comment]
It is true that it does not always work. But still a lot better than fixed limit.

I have used this for a month for price limit, and it does work really well. So no averaging, just last price.

```
{{ ((state_attr('sensor.nordpool_kwh_fi_eur_3_10_01',
            'tomorrow')[23]) )}}
```

**Comment by jonasbkarlsson** [comment]
OK, time to look into this.... 

So what are your learnings from this? The latest suggestion, to set the price limit to the last price tomorrow, sound reasonable to me. Is that what I should do?

**Comment by janneho** [comment]
That is what i have doing for last year. Automation sets price llimit to last price*0.95 (if negative then last price*1.05).

**Comment by jonasbkarlsson** [comment]
Interesting. So 5% lower than the last price next day. How do you explain the 5%? Do you think it will make sense with those 5% in different countries?

**Comment by janneho** [comment]
It works here (in finland). Not sure how prices works in different countries.

Electricity consumption is lower at nights, cheapest prices are allmost allways after midnight.

Below are average prices per hour for year 2024.
![Screenshot_20250108_201621_com_android_chrome_ChromeTabbedActivity](https://github.com/user-attachments/assets/bea29abe-fad9-40cd-912a-38cc4ae75f4c)

**Comment by jonasbkarlsson** [comment]
I think it will work well in Sweden too.

How did you make that graph?

Also, if you were to name this feature, do you have suggestions? And how to handle it in relatation to the current "opportunistic charging"

1) Give it a complete different name, and handle it separately from "opportunistic charging".
2) Call it "opportunistic charging 2", but handle it separately from "opportunistic charging".
3) Add a switch (e.g. switch.ev_smart_charging_opportunistic_charging_modifier) that will modified the rules for "opportunistic charging".

I think your inital suggestion was 3). I think 1) would be better than 2).

**Comment by janneho** [comment]
Graph is from [liukuri](https://liukuri.fi/tuntihinnat).

Maybe just alternative oppirtunic charging. Not sure if that 5% works everywhere, so maybe setting for that (bit like oppirtunistic level slider).

I am ok with 2. 

BTW HA Nordpool addon does not get the last price (in finland), so i am using entso-e. Last price that we have is first price day after tomorrow. So it does not fit in nordpools raw tomorrow.

**Comment by jonasbkarlsson** [comment]
Ok, then I will do it this way:

`switch.ev_smart_charging_opportunistic_type2_charging`

Activates opportunistic type 2 charging. See the desciption of the configuration entity `number.ev_smart_charging_opportunistic_type2_level`.

`number.ev_smart_charging_opportunistic_type2_level`

If the `switch.ev_smart_charging_opportunistic_type2_charging` switch is activated, the price limit will be set based on the the price at the end of the day tomorrow, "price at the end of the day tomorrow" * Opportunistic type2 level / 100. For example, if the Opportunistic type2 level is set to 90, the price limit will be set to 90% of the "price at the end of the day tomorrow". If the "price at the end of the day tomorrow" is negative, the price limit will be "price at the end of the day tomorrow" * (200 - Opportunistic type2 level) / 100. If `switch.ev_smart_charging_apply_price_limit` is also activated, the lowest of the two price limits will be used. Valid values min=0, step=1, max=200. Can be set by service call number.set_value.

**Comment by janneho** [comment]
I would change "price at the end of the day tomorrow" to "last available price"

This is my entso-E entity.
Last price end of tomorrow is (0.12757), last price in finland is actually first price of day after tomorrow (0.11701).


```
state_class: measurement
prices_today: 
- time: '2025-01-09 00:00:00+02:00'
  price: 0.13571
- time: '2025-01-09 01:00:00+02:00'
  price: 0.11611
- time: '2025-01-09 02:00:00+02:00'
  price: 0.11326
- time: '2025-01-09 03:00:00+02:00'
  price: 0.11228
- time: '2025-01-09 04:00:00+02:00'
  price: 0.11309
- time: '2025-01-09 05:00:00+02:00'
  price: 0.11567
- time: '2025-01-09 06:00:00+02:00'
  price: 0.13125
- time: '2025-01-09 07:00:00+02:00'
  price: 0.16474
- time: '2025-01-09 08:00:00+02:00'
  price: 0.26925
- time: '2025-01-09 09:00:00+02:00'
  price: 0.28188
- time: '2025-01-09 10:00:00+02:00'
  price: 0.27188
- time: '2025-01-09 11:00:00+02:00'
  price: 0.26037
- time: '2025-01-09 12:00:00+02:00'
  price: 0.26044
- time: '2025-01-09 13:00:00+02:00'
  price: 0.24432
- time: '2025-01-09 14:00:00+02:00'
  price: 0.23509
- time: '2025-01-09 15:00:00+02:00'
  price: 0.23878
- time: '2025-01-09 16:00:00+02:00'
  price: 0.24586
- time: '2025-01-09 17:00:00+02:00'
  price: 0.24783
- time: '2025-01-09 18:00:00+02:00'
  price: 0.25027
- time: '2025-01-09 19:00:00+02:00'
  price: 0.25427
- time: '2025-01-09 20:00:00+02:00'
  price: 0.24059
- time: '2025-01-09 21:00:00+02:00'
  price: 0.22854
- time: '2025-01-09 22:00:00+02:00'
  price: 0.20543
- time: '2025-01-09 23:00:00+02:00'
  price: 0.20202

prices_tomorrow: 
- time: '2025-01-10 00:00:00+02:00'
  price: 0.16401
- time: '2025-01-10 01:00:00+02:00'
  price: 0.16306
- time: '2025-01-10 02:00:00+02:00'
  price: 0.15018
- time: '2025-01-10 03:00:00+02:00'
  price: 0.14574
- time: '2025-01-10 04:00:00+02:00'
  price: 0.1407
- time: '2025-01-10 05:00:00+02:00'
  price: 0.14311
- time: '2025-01-10 06:00:00+02:00'
  price: 0.15565
- time: '2025-01-10 07:00:00+02:00'
  price: 0.20379
- time: '2025-01-10 08:00:00+02:00'
  price: 0.23444
- time: '2025-01-10 09:00:00+02:00'
  price: 0.25411
- time: '2025-01-10 10:00:00+02:00'
  price: 0.24909
- time: '2025-01-10 11:00:00+02:00'
  price: 0.23335
- time: '2025-01-10 12:00:00+02:00'
  price: 0.22129
- time: '2025-01-10 13:00:00+02:00'
  price: 0.21523
- time: '2025-01-10 14:00:00+02:00'
  price: 0.20856
- time: '2025-01-10 15:00:00+02:00'
  price: 0.21484
- time: '2025-01-10 16:00:00+02:00'
  price: 0.23448
- time: '2025-01-10 17:00:00+02:00'
  price: 0.23981
- time: '2025-01-10 18:00:00+02:00'
  price: 0.25028
- time: '2025-01-10 19:00:00+02:00'
  price: 0.24739
- time: '2025-01-10 20:00:00+02:00'
  price: 0.19729
- time: '2025-01-10 21:00:00+02:00'
  price: 0.14591
- time: '2025-01-10 22:00:00+02:00'
  price: 0.13553
- time: '2025-01-10 23:00:00+02:00'
  price: 0.12757

prices: 
- time: '2025-01-09 00:00:00+02:00'
  price: 0.13571
- time: '2025-01-09 01:00:00+02:00'
  price: 0.11611
- time: '2025-01-09 02:00:00+02:00'
  price: 0.11326
- time: '2025-01-09 03:00:00+02:00'
  price: 0.11228
- time: '2025-01-09 04:00:00+02:00'
  price: 0.11309
- time: '2025-01-09 05:00:00+02:00'
  price: 0.11567
- time: '2025-01-09 06:00:00+02:00'
  price: 0.13125
- time: '2025-01-09 07:00:00+02:00'
  price: 0.16474
- time: '2025-01-09 08:00:00+02:00'
  price: 0.26925
- time: '2025-01-09 09:00:00+02:00'
  price: 0.28188
- time: '2025-01-09 10:00:00+02:00'
  price: 0.27188
- time: '2025-01-09 11:00:00+02:00'
  price: 0.26037
- time: '2025-01-09 12:00:00+02:00'
  price: 0.26044
- time: '2025-01-09 13:00:00+02:00'
  price: 0.24432
- time: '2025-01-09 14:00:00+02:00'
  price: 0.23509
- time: '2025-01-09 15:00:00+02:00'
  price: 0.23878
- time: '2025-01-09 16:00:00+02:00'
  price: 0.24586
- time: '2025-01-09 17:00:00+02:00'
  price: 0.24783
- time: '2025-01-09 18:00:00+02:00'
  price: 0.25027
- time: '2025-01-09 19:00:00+02:00'
  price: 0.25427
- time: '2025-01-09 20:00:00+02:00'
  price: 0.24059
- time: '2025-01-09 21:00:00+02:00'
  price: 0.22854
- time: '2025-01-09 22:00:00+02:00'
  price: 0.20543
- time: '2025-01-09 23:00:00+02:00'
  price: 0.20202
- time: '2025-01-10 00:00:00+02:00'
  price: 0.16401
- time: '2025-01-10 01:00:00+02:00'
  price: 0.16306
- time: '2025-01-10 02:00:00+02:00'
  price: 0.15018
- time: '2025-01-10 03:00:00+02:00'
  price: 0.14574
- time: '2025-01-10 04:00:00+02:00'
  price: 0.1407
- time: '2025-01-10 05:00:00+02:00'
  price: 0.14311
- time: '2025-01-10 06:00:00+02:00'
  price: 0.15565
- time: '2025-01-10 07:00:00+02:00'
  price: 0.20379
- time: '2025-01-10 08:00:00+02:00'
  price: 0.23444
- time: '2025-01-10 09:00:00+02:00'
  price: 0.25411
- time: '2025-01-10 10:00:00+02:00'
  price: 0.24909
- time: '2025-01-10 11:00:00+02:00'
  price: 0.23335
- time: '2025-01-10 12:00:00+02:00'
  price: 0.22129
- time: '2025-01-10 13:00:00+02:00'
  price: 0.21523
- time: '2025-01-10 14:00:00+02:00'
  price: 0.20856
- time: '2025-01-10 15:00:00+02:00'
  price: 0.21484
- time: '2025-01-10 16:00:00+02:00'
  price: 0.23448
- time: '2025-01-10 17:00:00+02:00'
  price: 0.23981
- time: '2025-01-10 18:00:00+02:00'
  price: 0.25028
- time: '2025-01-10 19:00:00+02:00'
  price: 0.24739
- time: '2025-01-10 20:00:00+02:00'
  price: 0.19729
- time: '2025-01-10 21:00:00+02:00'
  price: 0.14591
- time: '2025-01-10 22:00:00+02:00'
  price: 0.13553
- time: '2025-01-10 23:00:00+02:00'
  price: 0.12757
- time: '2025-01-11 00:00:00+02:00'
  price: 0.11701
```
