### ISSUE TITLE
Smart charging not updated

### ISSUE THREAD

**Issue by molcam** [jonasbkarlsson/ev_smart_charging#115]
## Version of the custom_component

Version 1.60
## Configuration
Describe your configuration here.

## Describe the bug
The smart charging on the curve (incl smart charging) is not updated. I have seen it several times that the curve is not updated and thereby, charging not activated during the night (when price is lowest). If I press the on/off switches in the intergration a few times then the smart price curve is updated but it is not done per default.

**Comment by jonasbkarlsson** [comment]
Sorry to hear about your troubles. What you describe could be an issuse that I have seen in v1.5.0. If so, then it should be fixed in v1.6.0. Could you please update to v1.6.0, and if you still see the problem, please let me know.

**Comment by molcam** [comment]
I actually am running v1.6.0 (wrote wrong one before)... So error seems to persist.

**Comment by jonasbkarlsson** [comment]
Which settings of the configuration entities do you have?
Do you have have live update of the EV SOC entity, or do you manually update it?

**Comment by molcam** [comment]
Yes, I have a live update. The EV SOC can say that it is e.g. 30% and the car is not connected. Smart charging is activated but when the car is connected, nothing happends. It does not update. Even tested if it was a graphical error but the charger did not start. Just a comment - love the integration when it works :-) Fantastic idea!

**Comment by jonasbkarlsson** [comment]
Do you update `switch.ev_smart_charging_ev_connected` to reflect that the car is connected to the charger, or not?

**Comment by jonasbkarlsson** [comment]
Can you go to `Settings -> Devices & Services -> Integrations -> EV Smart Charging -> 1 device` and let me know what settings and values you have in "Controls" and in "Settings"? (A sceenshot of those parts would be fine.)

At what time of the day have you expirenced that the charging schedule hasn't been updated? Before the prices are updated (prices are updated shortly after 13:00) or after the prices have been updated, or both before and after?

**Comment by molcam** [comment]
Hi!
Generally, I will have to switch off all controls and then set them to on again before the smart charge is updated. 
Apply pricelimit: off
Continous chargin: on
Ev Connected: on (This is incorrect since the car is not connected at the moment - should this reflect if the car is connected? Then this is not updated correctly)
Keep charger on: on
Opperistic : off
Smart charging activated: on

Charge compeltion time: 7
Charge start time: Nobe
Charge speed: 15
Electric price limit: 0.0
Minimum EV SOC: 0
Opernistic level: 50%.

**Comment by jonasbkarlsson** [comment]
Thanks for the information. I have tested a little bit, but not so much yet.

I want to check one thing.

There are two cases when the charging schedule by design will not be updated when you change some of the settings.
- During the time between the completion time (07:00 in your case) and the time when the prices for tomorrow comes (shortly after 13:00)
- While scheduled charging is on-going

Can you confirm that the issue you have seen has happen after 14:00 and when there has not been any charging on-going?

**Comment by molcam** [comment]
Hi!
Yes it is after 14.00. See attached files.

Den tis 31 jan. 2023 12:59Jonas Karlsson ***@***.***> skrev:

**Comment by jonasbkarlsson** [comment]
Thanks for the confirmation. Your message said "see attached files", but I can't see any files. Only the orignal message you replied too (and I removed some links from it).

I used your settings yesterday, and it work ok for me. I will continue using them to see if I can trigger the problem.

Is the problem happen often? Every day?

Would you be able to provide a debug-file? 

To do that you need [follow the instructions](https://home-assistant-ocpp.readthedocs.io/en/latest/debugging.html) here, but to search for `ev_smart_charging` instead of ocpp.

And you would need to add the following
```
logger:
  default: info
  logs:
    custom_components.ev_smart_charging: debug
```

to the file `configuration.yaml` and restart Home Assistant.

**Comment by jonasbkarlsson** [comment]
Now I found the problem. 

If you want to use `switch.ev_smart_charging_keep_charger_on` =  `on`, then you must make sure that `switch.ev_smart_charging_ev_connected` is set to `on` when the car is connected and set to `off` when the car is not connected. 

The best way to achieve this is with an automation. [One example is provided here](https://github.com/jonasbkarlsson/ev_smart_charging#example-of-automation-to-inform-the-integration-that-the-ev-is-connected-to-the-charger), but you might need to adjust it depending on with charger and/or car you have.

You can turn `switch.ev_smart_charging_ev_connected` on and off manually, but that's not really a nice solution.

**Comment by molcam** [comment]
Fantatic! I will try it out :)

Den tis 31 jan. 2023 21:44Jonas Karlsson ***@***.***> skrev:

**Comment by molcam** [comment]
Hi!
I tried it but unfortunately the automation did not work. I think I need some explanation to the EV Smart Charging - EV connected automation such as. What parameters needs to be defined and what are part of your integration. E.g.
sensor.ocpp_status_connector
switch.turn_on
switch.ev_smart_charging_ev_connected
Thank you!

**Comment by jonasbkarlsson** [comment]
Which integration do you use to control your charging box?

**Comment by molcam** [comment]
Garo

**Comment by jonasbkarlsson** [comment]
You should have an entity called `sensor.YOUR_GARO_status`. Check what value it has when you use your charger.

If it has the value "Vehicle not connected" when the car is disconnected, and something else when connected, then something like following could work. Replace "YOUR_GARO" with the name you have.

```
alias: EV Smart Charging - EV connected
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.YOUR_GARO_status
condition: []
action:
  - if:
      - condition: state
        entity_id: sensor.YOUR_GARO_status
        state: Vehicle not connected
    then:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.ev_smart_charging_ev_connected
    else:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.ev_smart_charging_ev_connected
mode: single
```

**Comment by molcam** [comment]
Thank you!
I tried the automation but there seems to be a problem - it does still not work. Not sure if there is a bugg with the GARO integration. The integration states "Vehicle connected" even though it is not connected to the car. This seem to be the standard message if car is not connected. If in fact it is connected it states either "Charging" when car is charging, "Charging Finished" connected and not charging anymore, "Charging Disabled" when charger disabled by user interface (or HA)...

**Comment by jonasbkarlsson** [comment]
To disable the charger, is that something this integration will do (using some automation), or are you talking about some other way you might disable the charger from HA?

If this integration does not disable the charger, then I would use the following. Please let me know if it works.

```
alias: EV Smart Charging - EV connected
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - sensor.YOUR_GARO_status
condition: []
action:
  - if:
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.YOUR_GARO_status
            state: Charging finished
          - condition: state
            entity_id: sensor.YOUR_GARO_status
            state: Charging
    then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.ev_smart_charging_ev_connected
    else:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.ev_smart_charging_ev_connected
```
