### ISSUE TITLE
Time offset by timezone?

### ISSUE THREAD

**Issue by tobixx** [jonasbkarlsson/ev_smart_charging#146]
Hi, 

the graph indicates that the charging should have been started already:

![time_offset](https://user-images.githubusercontent.com/211389/222690246-24d7d5e6-a1c3-48c3-a813-be401135171f.png)

but not yet started as seen in the state.

Data indicates a one hour offset in opposite to the graph:

```
current_price: 0.131
EV SOC: 70
EV target SOC: 100
Charging status: Waiting for charging to begin
Charging is planned: true
Charging start time: 2023-03-03T11:00:00+01:00
Charging stop time: 2023-03-03T16:00:00+01:00
Charging number of hours: 5
raw_two_days: 
- start: '2023-03-03T00:00:00+01:00'
  end: '2023-03-03T01:00:00+01:00'
  value: 0.14
- start: '2023-03-03T01:00:00+01:00'
  end: '2023-03-03T02:00:00+01:00'
  value: 0.13
- start: '2023-03-03T02:00:00+01:00'
  end: '2023-03-03T03:00:00+01:00'
  value: 0.131
- start: '2023-03-03T03:00:00+01:00'
  end: '2023-03-03T04:00:00+01:00'
  value: 0.128
- start: '2023-03-03T04:00:00+01:00'
  end: '2023-03-03T05:00:00+01:00'
  value: 0.128
- start: '2023-03-03T05:00:00+01:00'
  end: '2023-03-03T06:00:00+01:00'
  value: 0.135
- start: '2023-03-03T06:00:00+01:00'
  end: '2023-03-03T07:00:00+01:00'
  value: 0.162
- start: '2023-03-03T07:00:00+01:00'
  end: '2023-03-03T08:00:00+01:00'
  value: 0.187
- start: '2023-03-03T08:00:00+01:00'
  end: '2023-03-03T09:00:00+01:00'
  value: 0.195
- start: '2023-03-03T09:00:00+01:00'
  end: '2023-03-03T10:00:00+01:00'
  value: 0.166
- start: '2023-03-03T10:00:00+01:00'
  end: '2023-03-03T11:00:00+01:00'
  value: 0.131
- start: '2023-03-03T11:00:00+01:00'
  end: '2023-03-03T12:00:00+01:00'
  value: 0.123
- start: '2023-03-03T12:00:00+01:00'
  end: '2023-03-03T13:00:00+01:00'
  value: 0.115
- start: '2023-03-03T13:00:00+01:00'
  end: '2023-03-03T14:00:00+01:00'
  value: 0.112
- start: '2023-03-03T14:00:00+01:00'
  end: '2023-03-03T15:00:00+01:00'
  value: 0.111
- start: '2023-03-03T15:00:00+01:00'
  end: '2023-03-03T16:00:00+01:00'
  value: 0.115
- start: '2023-03-03T16:00:00+01:00'
  end: '2023-03-03T17:00:00+01:00'
  value: 0.129
- start: '2023-03-03T17:00:00+01:00'
  end: '2023-03-03T18:00:00+01:00'
  value: 0.156
- start: '2023-03-03T18:00:00+01:00'
  end: '2023-03-03T19:00:00+01:00'
  value: 0.165
- start: '2023-03-03T19:00:00+01:00'
  end: '2023-03-03T20:00:00+01:00'
  value: 0.153
- start: '2023-03-03T20:00:00+01:00'
  end: '2023-03-03T21:00:00+01:00'
  value: 0.133
- start: '2023-03-03T21:00:00+01:00'
  end: '2023-03-03T22:00:00+01:00'
  value: 0.122
- start: '2023-03-03T22:00:00+01:00'
  end: '2023-03-03T23:00:00+01:00'
  value: 0.112
- start: '2023-03-03T23:00:00+01:00'
  end: '2023-03-04T00:00:00+01:00'
  value: 0.102

charging_schedule: 
- start: '2023-03-03T00:00:00+01:00'
  end: '2023-03-03T01:00:00+01:00'
  value: 0
- start: '2023-03-03T01:00:00+01:00'
  end: '2023-03-03T02:00:00+01:00'
  value: 0
- start: '2023-03-03T02:00:00+01:00'
  end: '2023-03-03T03:00:00+01:00'
  value: 0
- start: '2023-03-03T03:00:00+01:00'
  end: '2023-03-03T04:00:00+01:00'
  value: 0
- start: '2023-03-03T04:00:00+01:00'
  end: '2023-03-03T05:00:00+01:00'
  value: 0
- start: '2023-03-03T05:00:00+01:00'
  end: '2023-03-03T06:00:00+01:00'
  value: 0
- start: '2023-03-03T06:00:00+01:00'
  end: '2023-03-03T07:00:00+01:00'
  value: 0
- start: '2023-03-03T07:00:00+01:00'
  end: '2023-03-03T08:00:00+01:00'
  value: 0
- start: '2023-03-03T08:00:00+01:00'
  end: '2023-03-03T09:00:00+01:00'
  value: 0
- start: '2023-03-03T09:00:00+01:00'
  end: '2023-03-03T10:00:00+01:00'
  value: 0
- start: '2023-03-03T10:00:00+01:00'
  end: '2023-03-03T11:00:00+01:00'
  value: 0
- start: '2023-03-03T11:00:00+01:00'
  end: '2023-03-03T12:00:00+01:00'
  value: 0.14625
- start: '2023-03-03T12:00:00+01:00'
  end: '2023-03-03T13:00:00+01:00'
  value: 0.14625
- start: '2023-03-03T13:00:00+01:00'
  end: '2023-03-03T14:00:00+01:00'
  value: 0.14625
- start: '2023-03-03T14:00:00+01:00'
  end: '2023-03-03T15:00:00+01:00'
  value: 0.14625
- start: '2023-03-03T15:00:00+01:00'
  end: '2023-03-03T16:00:00+01:00'
  value: 0.14625
- start: '2023-03-03T16:00:00+01:00'
  end: '2023-03-03T17:00:00+01:00'
  value: 0
- start: '2023-03-03T17:00:00+01:00'
  end: '2023-03-03T18:00:00+01:00'
  value: 0
- start: '2023-03-03T18:00:00+01:00'
  end: '2023-03-03T19:00:00+01:00'
  value: 0
- start: '2023-03-03T19:00:00+01:00'
  end: '2023-03-03T20:00:00+01:00'
  value: 0
- start: '2023-03-03T20:00:00+01:00'
  end: '2023-03-03T21:00:00+01:00'
  value: 0
- start: '2023-03-03T21:00:00+01:00'
  end: '2023-03-03T22:00:00+01:00'
  value: 0
- start: '2023-03-03T22:00:00+01:00'
  end: '2023-03-03T23:00:00+01:00'
  value: 0
- start: '2023-03-03T23:00:00+01:00'
  end: '2023-03-04T00:00:00+01:00'
  value: 0
```

**Comment by jonasbkarlsson** [comment]
Hi!
Seems like the screenshots are taken about 10:50. Is that correct?
The charging is planned to start 11:00, so it seems correct that charging has not started.

I have struggled a bit to make the Apexcharts-card example. How about the following? Note that I added `offset: '-30min'`.
```
      - entity: sensor.ev_smart_charging_charging
        name: Charging
        data_generator: >
          return entity.attributes.charging_schedule.map((entry) => { return
          [new Date(entry.start), entry.value]; });
        type: area
        color: black
        offset: '-30min'
        show:
          in_header: false
        extend_to: false

```
You might want to replace the `type: area` with `type: column` to make it clearer.
