### ISSUE TITLE
Reconfigure when you set start time later than now

### ISSUE THREAD

**Issue by woopstar** [jonasbkarlsson/ev_smart_charging#170]
If you set the start time before now, the sensor is updated and charge schedules are re-calculated.

If you then, while it's charging, set the start time to later, the sensor is not updated and the schedules are not re-calculated.

I just tested by setting the start time to 14.00. Charging began. Then changed the start time to 15.00 as only thing, but the charging did not stop and the charge schedule was not re-calculated to the new start time.

Running version v1.8.0

**Comment by jonasbkarlsson** [comment]
Yes, that's how it's implemented. "When the automatic charging has started, changes of settings will not have any effect." If you need to stop an on-going charging in this case, you can deactive/active the integration by toggling the `switch.ev_smart_charging_smart_charging_activated`.

**Comment by woopstar** [comment]
So if you change the start time - let's say from automation - and it's already running, then you need to deactivate/activate it again.

**Comment by woopstar** [comment]
Something like this:

```yaml
  - if:
      - condition: time
        before: select.ev_smart_charging_charge_completion_time
      - condition: state
        entity_id: sensor.ev_smart_charging_charging
        state: "on"
    then:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.ev_smart_charging_smart_charging_activated
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.ev_smart_charging_smart_charging_activated
```
