### ISSUE TITLE
My ID4 not starting with Charging

### ISSUE THREAD

**Issue by janss028** [jonasbkarlsson/ev_smart_charging#176]
## Version of the custom_component

Version x.x.x

## Configuration
Describe your configuration here.

## Debug log

```text

Add your logs here.

```

**Comment by janss028** [comment]
I'm new with this intergration.

After installation of the integration my ID4 not starting with charging:
![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/06fcdb74-52ae-4b7e-acc1-bebdb9e68536)

![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/3b11c242-1096-461e-9744-1849f1c4d257)

My Settings:
![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/f05aefb7-653c-4ce4-a81b-fd81744402db)

If I put the charge button of My ID4
![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/56142378-ea59-452d-ba62-dedfc298f6b9)

I get the following error message:
![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/0783841f-d0fa-47e1-bd63-365383d06ee2)


Can you tell me what I doing wrong?

Best Regards,
Ron

**Comment by janneho** [comment]
I do not have VW, but can you try with automation method?
Leave charger configuration entity empty on integration config, and try with two automations below.

Hope it works...

Start charging automation:
```
alias: EV Smart Charging - Start
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - sensor.ev_smart_charging_charging
    from: "off"
    to: "on"
condition: []
action:
  - service: button.press
      target:
        entity_id: button.id4_start_charging
```


Stop charging automation:
```
alias: EV Smart Charging - Stop
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - sensor.ev_smart_charging_charging
    from: "on"
    to: "off"
condition: []
action:
  - service: button.press
      target:
        entity_id: button.id4_stop_charging
```

**Comment by janss028** [comment]
@jonasbkarlsson , @Obelixje my charger is not controlled by is also not possible to controll it with HA.
Yesterday evening I did a small test with the solution of @Obelixje and I think this will work. This weekend I will do e new test and will inform you.

Thank you in advance

**Comment by janss028** [comment]
@jonasbkarlsson 
What do you recommend if the charger can't work with HA. I think my ID4 should initiate charging?

As you can see below, the status is charging but my car is not connected

![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/22b8664d-fa41-420a-a9b3-27d4a7c1cc60)

**Comment by jonasbkarlsson** [comment]
If the charging is controlled via the car, then the recommendation is to make an automation that controls the `switch.ev_smart_charging_ev_connected`, provinding information to the integration that the car is connected to the charger.

The easiest way to do that is, once again, to get information from the charger. See [this example](https://github.com/jonasbkarlsson/ev_smart_charging#example-of-automation-to-inform-the-integration-that-the-ev-is-connected-to-the-charger).

Now, if that is not posssible, then I guess you need to start being a bit creative.
- An automation that use the car's position?
- And as last resort, just manually switch the `switch.ev_smart_charging_ev_connected` on and off.

**Comment by janneho** [comment]
Do you have sensor sensor.id4_plug_connection_state? Or something like that? Could it be used?

**Comment by janss028** [comment]
@janneho Yes, I have. Do you have it working and if yes, can you help me?

best regards,
Ron

**Comment by janneho** [comment]
Can you check state of sensor.id4_plug_connection_state when charger is connected, and when it is unplugged from car?

**Comment by janss028** [comment]
HI @janneho 

The status is as below: 

connected
<img width="313" alt="image" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/0ec9cf1d-1a1c-4f8b-ad78-645b25ad64a0">

disconnected
<img width="320" alt="image" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/90012dc7-845d-4d4f-9ce3-d126ffbaaaa2">

I create the automation below:

alias: EV Smart Charging - EV connected
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.id4_plug_connection_state
condition:
  - condition: device
    device_id: e0f08d93788f2eedae712557a654494c
    domain: device_tracker
    entity_id: device_tracker.id4_tracker
    type: is_home
action:
  - if:
      - condition: state
        entity_id: sensor.id4_plug_connection_state
        state: connected
    then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.ev_smart_charging_ev_connected
    else:
      - if:
          - condition: state
            entity_id: sensor.id4_plug_connection_state
            state: disconnected
        then:
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.ev_smart_charging_ev_connected
mode: single

and put it in the configuration below:

<img width="253" alt="image" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/3a1f3997-8add-4de5-aebe-265becadef3d">

Is this coreect?

Do I need also the follow automations:

alias: EV Smart Charging - Start
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - sensor.ev_smart_charging_charging
    from: "off"
    to: "on"
condition: []
action:
  - service: button.press
    target:
      entity_id: button.id4_start_charging

and

alias: EV Smart Charging - Stop
description: ""
mode: single
trigger:
  - platform: state
    entity_id:
      - sensor.ev_smart_charging_charging
    from: "on"
    to: "off"
condition: []
action:
  - service: button.press
    target:
      entity_id: button.id4_stop_charging

Thank you for your help

**Comment by janneho** [comment]
Leave charger control switch empty in configuration. You need all 3 automations.
Two of them starts and stops charging in car when integration says so.
Third automation tells that car is home, and charger is plugged in to car. Automation seems about right.

Then i suggest that you automation, that turns integration off, and charging on when car is not home. And vice versa.
If you do not have that, when you charge for example in fast charger on road, integration continues controlling charging (not charging if price is high).

I do not have volkswagen, so no guarantees on this. Report if all is ok, or not.

**Comment by janss028** [comment]
Hi @janneho 

It is not possible to remove in setting:
<img width="245" alt="image" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/0adef872-61d0-4a1c-881e-a31c8d3cb406">

If you remove it and save it, it is back after open de configuration again.

**Comment by janneho** [comment]
Can you add one space and nothing more?

**Comment by janss028** [comment]
That helps :)

The manual start / stop works fine.
Now wait till tomorrow to see if everything works fine.

<img width="242" alt="image" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/d093c83f-0132-4991-ae13-d99d8ef14a88">


I will give you an update.

**Comment by janss028** [comment]
Hi,
The car is not starting with charging.

<img width="407" alt="image" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/fbcd42d9-25fc-4aee-aa9d-11bc80babb69">

It is connected and at home.
I’m using the automation below:

alias: EV Smart Charging - EV connected
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.id4_plug_connection_state
condition:
  - condition: device
    device_id: e0f08d93788f2eedae712557a654494c
    domain: device_tracker
    entity_id: device_tracker.id4_tracker
    type: is_home
action:
  - if:
      - condition: state
        entity_id: sensor.id4_plug_connection_state
        state: connected
    then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.ev_smart_charging_ev_connected
    else:
      - if:
          - condition: state
            entity_id: sensor.id4_plug_connection_state
            state: Available
        then:
          - service: switch.turn_off
            data: {}
            target:
              entity_id: switch.ev_smart_charging_ev_connected
mode: single

Manual I can start and stop charging.

<img width="404" alt="image" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/2dc097db-b5f2-4521-9210-4ae4a2d139d5">

Do you know what is wrong?

**Comment by janneho** [comment]
What does it look like in settings -> Devices and services -> ev smart charging. Mine is like this

![Screenshot_20230514-215556](https://github.com/jonasbkarlsson/ev_smart_charging/assets/2905409/e17ac09d-b572-4aad-a340-6231acdd5f3e)

Is ev connected on?

**Comment by janss028** [comment]
@janneho 

below my overview

<img width="151" alt="image" src="https://github.com/jonasbkarlsson/ev_smart_charging/assets/79377231/2835a8a9-3706-4429-991a-9251df9c51ea">

**Comment by janneho** [comment]
I can not think why it should not work. Below is from documentation. If manual start and stop works, i do not know why scheduled charging is not working.

Verifying the configuration

To verify that the integration is able to control the charging, go to Settings -> Devices & Services -> Integrations -> EV Smart Charging -> 1 device -> Controls.

    Connect the EV to the charger.
    PRESS the Manually start charging.
    Check that charging is started.
    PRESS the Manually stop charging.
    Check that charging is stopped.
    PRESS the Manually start charging.
    Check that charging is started.

If the above works, the integration is able to control the charging.

**Comment by janss028** [comment]
Hi @janneho 

Charging works fine. Thank you for your help.

I have a another question. As example the care should start with charging at 14.00. If I connect my car at the charger at 10.00 it start already with charging an I must it switch off manual with the STOP charging button. Charging stops and at 14.00 it starts with charging. How can I change that charging not start after I connect the cable but start with charging if the integration says start with charging?

Thanks in advance.
Ron

**Comment by janneho** [comment]
Try to add charge stop in EV connected script, that is what I have done.
Something like this:

```
alias: EV Smart Charging - EV connected
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.id4_plug_connection_state
         condition:
  - condition: device
    device_id: e0f08d93788f2eedae712557a654494c
    domain: device_tracker
    entity_id: device_tracker.id4_tracker
    type: is_home
action:
  - if:
    - condition: state
       entity_id: sensor.id4_plug_connection_state
       state: connected
    then:
      - service: switch.turn_on
        data: {}
        target:
        entity_id: switch.ev_smart_charging_ev_connected
      - service: button.press
        target:
        entity_id: button.id4_stop_charging
        else:
         - if:
            condition: state
            entity_id: sensor.id4_plug_connection_state
            state: Available
        then:
           service: switch.turn_off
           data: {}
           target:
           entity_id: switch.ev_smart_charging_ev_connected
           mode: single
```

**Comment by enoch85** [comment]
Sorry for hijacking this a bit, I'm just wondering if I actually need to set any values in "Low Price" and "Electricity Price limit"?

![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/4511254/0550e45b-1e21-46b6-80c2-f8309cb4bcf5)

I have the same issue on my Tesla that the charging isn't started. I did the manual test as per documentation, and it worked. But charging won't start even if it's the lowest price on todays curve: 

![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/4511254/8b7706e3-2b26-4b2f-95d7-c6c33f69980a)

I want the charging to be done at 05:00, and it can start whenever during the day, preferably Continuously.

**Comment by enoch85** [comment]
Sorry for noise, I've now solved it.

**Comment by enoch85** [comment]
:wave: 

I experience similar issues for my Tesla Model 3. 

What happens is that the car goes to deep sleep, and makes all the entities unavailable, which in turn makes EV Smart think that the car is not connected/available at all and changes to "No charging planned".

I'm experimenting with waking up the car now `if` charging is planned, by manually pressing the wake up button that the car have (in another automation). I already have the recommended automation in place when connecting and disconnecting the car, but that doesn't help since all the entities are gone anyway.

My wifes VW e-UP! works without any issues at all on the same settings. Until then, does anyone have any idea how to fix this in the best possible way?

I will keep this issue updated with my progress.

**Comment by jonasbkarlsson** [comment]
@enoch85 is going to deep sleep and make all the entities unavailable to common behaviour for all Teslas? If so, then it sounds like a major problem. Strange that I haven't heard (much) about it.

For me, it would have been better if the Tesla integration kept the last know values instead of making the entities unavailable...

**Comment by enoch85** [comment]
@jonasbkarlsson 

> is going to deep sleep and make all the entities unavailable to common behaviour for all Teslas? 

I don't know, but I find the car to be very energy conserving, only loosing like 1% over several days if I don't touch it. So I guess, yes, it's a problem. The car will wake up if you plug a charge cable in it (or start charging), but with the entities unavailable it doesn't matter since charging won't start anyway. Would the setting "Keep charger on" help me here?

Right now I have this automation (which worked perfectly fine last night):

```
alias: Vakna Tesla!
description: Dags att ladda. :)
trigger:
  - platform: time
    at: "23:00:00"
condition:
  - condition: state
    entity_id: sensor.ev_smart_charging_charging
    attribute: Charging is planned
    state: true
action:
  - device_id: 8fc8504659b7162e4270b730466060f4
    domain: button
    entity_id: 243c1fb8746cb0cc34c5038f09e81cb7
    type: press
  - delay:
      hours: 3
      minutes: 0
      seconds: 0
      milliseconds: 0
    enabled: true
  - device_id: 8fc8504659b7162e4270b730466060f4
    domain: button
    entity_id: 243c1fb8746cb0cc34c5038f09e81cb7
    type: press
    enabled: true
mode: single
```

![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/4511254/6465791b-734f-4354-bae4-1d58d1167413)

Usually it goes to sleep around 00:00 if I leave it with charge plugged at around 17:00-18:00, hence the time trigger at 23:00 which will press the wake up button and then do the same thing 3 hours later (charging usually occurs between 01:00-04:00.

> For me, it would have been better if the Tesla integration kept the last know values instead of making the entities unavailable...

Agreed. I'm using [this integration](https://github.com/alandtse/tesla), so maybe it's time for an issue report? :)

It charged last night, and now I have this:

![image](https://github.com/jonasbkarlsson/ev_smart_charging/assets/4511254/d0d5de84-db0e-4aea-94a0-3b7b721e8d7e)

Maybe if you could save the data in your integration instead, I don't know what's best?
