### ISSUE TITLE
Support for multiple chargers

### ISSUE THREAD

**Issue by mikeSwe77** [jonasbkarlsson/ev_smart_charging#177]
More and more people have more than one EV which in turn result in more than one charger.
It would be wonderful if we would be able to gain support to control more than one charger.

**Comment by jonasbkarlsson** [comment]
It is possible to create multiple instances of the integration. So if each EV has its own charger, then it should work. 

There will however not be any coordination between the charging plans, so if there are any limitation in available power, that will not be automatically handled by the integration.

**Comment by jonasbkarlsson** [comment]
I might add coordination between multiple instances of the integration in the future. But I  can't promise when (or even if) I will be able to do that. I close this issue for the time being.

**Comment by svendhoest** [comment]
Btw. I made a small hacky sensor for my sons golf-e that is not online, So it will always return 60% or tesla SoC if it's below 60%. That way ev smart charger will always plan a charging session, and we can share the charger.

```
sensor:
  - platform: template
    sensors:
      min_battery_level:
        friendly_name: "Minimum Battery Level"
        unit_of_measurement: "%"
        value_template: "{{ min(60, states('sensor.lizzo_battery') | int) }}"
```
