### ISSUE TITLE
Weekday and weekend selection

### ISSUE THREAD

**Issue by MAFL74** [jonasbkarlsson/ev_smart_charging#259]
**Is your feature request related to a problem? Please describe.**
Not related to any problem.

**Describe the solution you'd like**
I'd like to have the option to choose weekend or specific days for charging. 

E.g.: Integration charging completing time set to 07.00.
If I plug in the car to the charger on friday afternoon the price is very low on Saturday evening, it would have been nice to be able to skip the "have to be done by 07.00" on Saturday morning, since configuration is set to it.

**Describe alternatives you've considered**
Use the poor Tibber integration app.

**Additional context**
No additional information.

**Comment by PeterAckermans** [comment]
This feature would really make weekend charging cheaper.

**Comment by Silkjaer** [comment]
Should be possible to change start/stop charge times with an automation, so it is done based on calendar events (work from home/or not) or by specific days.

**Comment by nimda5** [comment]
Done something similar with automation. Run at 13:30 when nordpool prices updated and set 09:00 if next day is workday and 12:00 if weekend.  

```
- id: ev_smart_charging_next_day_completion_time_change
  alias: EV smart charging completion time change for next day
  description: Set EV charge completion time based on whether tomorrow is a workday
  trigger:
    - platform: time
      at: "13:30:00"
  action:
    - choose:
        - conditions:
            - condition: template
              value_template: >
                {{ (now() + timedelta(days=1)).weekday() in [0, 1, 2, 3, 4] }}
          sequence:
            - service: select.select_option
              target:
                entity_id: select.ev_smart_charging_charge_completion_time
              data:
                option: "09:00"
      default:
        - service: select.select_option
          target:
            entity_id: select.ev_smart_charging_charge_completion_time
          data:
            option: "12:00"
  mode: single
```
