### ISSUE TITLE
Solar charging

### ISSUE THREAD

**Issue by maand75** [jonasbkarlsson/ev_smart_charging#265]
Hi,
would be Nice to integrate solar power so the car starts to charge depending on how much solar power you are producing

I have done this already in my own integration but through it would be a Nice additional feature to add?

If you want i can show you how i have implemented it.

**Comment by AndersHoglund** [comment]
I would like to have this feature too. 
@maand75 If you have a solution, implement it and issue a PR. This is how open source works.....
/A

**Comment by maand75** [comment]
Ill see if i manage it, i have just implementera it with some additional automation rules so i need to check how to extend your solution and if i can do it so it more independable of ev type

//Mathias
________________________________

**Comment by pluskal** [comment]
Hi guys, here is my automation to limit output current (A) for tesla it that helps in your effort.

I tried to keep it as simple as possible while extracting variables so it can be tested / verified  while modeling different conditions.

```
alias: "[Tesla] Charge on solar power"
description: ""
trigger:
  - platform: state
    entity_id: sensor.rct_power_storage_grid_power
condition:
  - condition: state
    entity_id: binary_sensor.raven_charger
    state: "on"
  - condition: state
    entity_id: device_tracker.raven_location_tracker
    state: home
action:
  - variables:
      grid_usage: "{{ states('sensor.rct_power_storage_grid_power') | float }}"
      max_charging_amps: "{{ state_attr('number.raven_charging_amps', 'max') | int }}"
      min_charging_amps: 1
      current_charging_amps: "{{ states('number.raven_charging_amps') | int }}"
      grid_voltage: "{{ states('sensor.rct_power_storage_grid_voltage_p2') | float }}"
  - target:
      entity_id: number.raven_charging_amps
    data:
      value: >
        {% set available_amps = (-grid_usage / grid_voltage) / 3 %}  {% set
        proposed_charging_amps = (available_amps + current_charging_amps) %} {%
        set proposed_charging_amps = ([proposed_charging_amps,
        min_charging_amps] | max) %} {% set new_charging_amp =
        ([proposed_charging_amps, max_charging_amps] | min | round(0, 'floor'))
        %} {{ new_charging_amp }}
    action: number.set_value
mode: single

```
