### ISSUE TITLE
Wiki suggestion

### ISSUE THREAD

**Issue by HolgerMiara** [jonasbkarlsson/ev_smart_charging#312]
Hi @jonasbkarlsson,  

I couldn't find a way to edit to the Wiki, but wanted to contribute to your [Charger >> Easee](https://github.com/jonasbkarlsson/ev_smart_charging/wiki/Easee) page. Feel free to review below and add it to the bottom of the Easee page of your Wiki. =)

### Automation to inform the integration that the EV is connected to the charger
The status sensor of the [Easee integration](https://github.com/nordicopen/easee_hass) can have the states `disconnected, awaiting_start, charging, ready_to_charge, completed` or `error`. The below automation is triggered every time the status of the sensor changes its state. Any other state than `disconnected` is being interpreted as a connected EV.

```
alias: EV Smart Charging - EV connection status
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.ehXXXXXX_status      (replace with your own charger ID)
condition: []
action:
  - if:
      - condition: state
        entity_id: sensor.ehXXXXXX_status      (replace with your own charger ID)
        state: disconnected
    then:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.ev_smart_charging_ev_connected
    else:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.ev_smart_charging_ev_connected
mode: single
``` 

HTH
