### ISSUE TITLE
Suggestions for readme.md corrections

### ISSUE THREAD

**Issue by raymond79nl** [jonasbkarlsson/ev_smart_charging#351]
## Version of the custom_component

Version 2.0.1

## Configuration
Used in combination with ENTSO-e and Tesla Fleet (for SOC status) as well as esphome-tesla-ble for charge start / stop switch.

## Describe the bug
Not a bug in SW, but I believe the readme contains an error: for the Entso-e integration, I had to use the entity called `sensor.average_electricity_price` instead of the suggested `sensor.average_electricity_price_today` to get things working.

There is also a minor typo in the lovelace UI template, last entity should be

```yaml
  - type: entity
    entity: sensor.ev_smart_charging_charging
    attribute: ev_soc
    name: EV SOC
    icon: mdi:battery-70
    unit: '%'
```

instead of
```yaml
  - type: entity
    entity: sensor.ev_smart_charging_charging
    attribute: EV SOC
    name: EV SOC
    icon: mdi:battery-70
    unit: '%'
```
