### ISSUE TITLE
No charging because switch not turned on

### ISSUE THREAD

**Issue by janjbrand** [jonasbkarlsson/ev_smart_charging#388]
## Configuration
Core 2025.1.3
Supervisor 2024.12.3
Operating System 14.2
Frontend 20250109.0

## Describe the bug
The integration does not activate the switch of my charger any more. Previously it worked fine and I don't know exactly what made it break. Fixed it with a simple automation, but based on it I have 2 questions.

1. What goes wrong? Here is the configuration:

![Image](https://github.com/user-attachments/assets/44914632-7d22-4920-835b-9ae861822da2)

Everything works fine, so it is calculating the cheapest moments etc. The status of the integration changes to 'charging', but the charger is left turned off.

This is the automation that fixes the issue:

```
alias: E. Fix EV Smart Charging
description: Toggle SmartEVSE power based on EV charging status.
triggers:
  - entity_id: sensor.ev_smart_charging_status
    trigger: state
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: sensor.ev_smart_charging_status
            state: charging
        sequence:
          - target:
              entity_id: switch.smartevse_power
            action: switch.turn_on
            data: {}
      - conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: sensor.ev_smart_charging_status
                state: charging
        sequence:
          - target:
              entity_id: switch.smartevse_power
            action: switch.turn_off
            data: {}
mode: restart
```

2. I do not get any error in the logs. Is it an idea to add that to the integration. To check whether the charger is in fact turned on if the charging status is 'charging'?

```
