### ISSUE TITLE
Cater for scheduled departure time (preheating etc)

### ISSUE THREAD

**Issue by tubalainen** [jonasbkarlsson/ev_smart_charging#39]
**Is your feature request related to a problem? Please describe.**
NEJ! :)

**Describe the solution you'd like**
Hej Jonas!
Would it be possible to implement an optional feature where the logic of this component could have a "forced window of active charger" to provide power to the car for scheduled departures and climatization of the EV car? 

Perhaps implementing a optional feature to set a "forced charger on window" feature where you can set start and stop time using an `input_datetime`?

**Describe alternatives you've considered**
- Preheat on battery
- Create my own timing automation "outside of the component"

**Additional context**
Like the orange line on the picture below.
![image](https://user-images.githubusercontent.com/26795429/201943602-6d4ba4c2-5d1f-4ff7-b178-286d29153d7f.png)

**Comment by tubalainen** [comment]
Mäh!

I might setup a couple of automations that will enable the charger during the morning hours.

Might not be such a great idea to do this within the component....???

**Comment by tubalainen** [comment]
```
- id: 'tesla_enable_climate_charging'
  alias: Tesla Enable Climate charging
  description: ''
  trigger:
    - id: 'on'
      platform: time
      at: '05:00:00'
    - id: 'off'
      platform: time
      at: '07:00:00'
  condition:
    - condition: state
      entity_id: device_tracker.my_tesla
      state: home
    - condition: state
      entity_id: sensor.wallbox_portal_status_description
      state: "Waiting"
  action:
    - service: 'switch.turn_{{ trigger.id }}'
      target:
        entity_id: switch.wallboxpulsar_charge_control
  mode: single
```
