### ISSUE TITLE
Dynamic setup parameters

### ISSUE THREAD

**Issue by ress23** [jonasbkarlsson/ev_smart_charging#51]
Is it possible to set parameters (max price, min soc, target soc, charging complete time) as dynamic inputs eg. input_number.max_price?

**Comment by ress23** [comment]
Figured out a way of creating dynamic SOC, and target SOC:
```
template:
  - sensor:
      - name: "EVSC SOC"
        unit_of_measurement: "%"
        device_class: battery
        state: >-
          {{ states('sensor.tesla_battery') }}
  - sensor:
      - name: "EVSC Target SOC"
        unit_of_measurement: "%"
        device_class: battery
        state: >-
          {{ states('input_number.evsc_target_soc') }}
```
They're obviously just fetching a value from another input at the moment but can be configured for multiple cars, scenarios etc.

Would love to have the same solution when it comes to assumed charging per hour, departure time, maximum price and minimum soc but they won't accept an entity input.
