### ISSUE TITLE
Rescheduling when car is plugged into charger

### ISSUE THREAD

**Issue by janneho** [jonasbkarlsson/ev_smart_charging#52]
As discussed in #48

Now it seems, that integration does not know if car is plugged in charger or not, so it is possible that charging is scheduled so that charging is started when car is not plugged in. If car is plugged in when charging is scheduled, charging is not triggered.
This also makes it possible to reschedule when car is plugged in, so that when you plug car in charging is scheduled from that time to "Charge completion time".
If you then unplug car, and plug it again later schedule is again updated (as you plugged car into charger again).

This way only change that car is not charged to "Minimum EV SOC" or "EV target SOC entity" (depending electricity price) is when you plug in so close "Charge completion time" that there is no time to charge it fully. In this case it still charges as much as possible (becouse every hour would be one of cheapest hours).

**Comment by jonasbkarlsson** [comment]
This is related to #40. 

I have been hesitating a bit about adding another input to the integration.

Instead, I have been thinking of monitoring the EV SOC entity. If the EV SOC is not increasing when charging has started, that means the car is not connected to the charger. And if this happens, the integration would wait a while, and then try to start the charging again. How about that?

**Comment by janneho** [comment]
How long should we wait for that? Hyundai/kia has limited amount of updates, so EV SOC update interval is 15-20min.

I have automation that runs when car is plugged in and if sensor.ev_smart_charging_charging is off, it stops charging. If it is on then start charging.

I have not been able to test this becouse cheapest hours have been after midnight.

**Comment by jonasbkarlsson** [comment]
So there might be EVs with slow updates of SOC? Hmm.

In that case, it's probably better to add a switch entity in the integration that the user can control with automations (or a template switch).

**Comment by jonasbkarlsson** [comment]
Have now done a [pre-release v1.3.0.dev](https://github.com/jonasbkarlsson/ev_smart_charging/releases/tag/v1.3.0.dev1). The code seem to work, but I would like to add a few more test cases and try it more in practice before making a normal release. Please try, and let me know if there is any problems.

So now there is a switch `switch.ev_smart_charging_ev_connected` that e.g. an automation can control to inform the integration that the EV is connected to the charger. The charging schedule will be recalculated when connected, if there is information about the electricity prices for tomorrow, i.e., typically from shortly after 13:00 and to 23:59. Charging should start if connected after midnight, but the charging schedule will not be recalculated.

```
alias: EV Connected
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.ev_charger_status (to be replaced with your entity)
condition: []
action:
  - if:
      - condition: state
        entity_id: sensor.ev_charger_status (to be replaced with your entity)
        state: "connected" (to be replaced with suitable state for your charger)
    then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.ev_smart_charging_ev_connected
    else:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.ev_smart_charging_ev_connected
mode: single
```
