### ISSUE TITLE
Add integration support for energidataservice to get prices

### ISSUE THREAD

**Issue by cnrd** [jonasbkarlsson/ev_smart_charging#87]
Add support for getting prices from https://github.com/MTrab/energidataservice

The format is very like nordpool, but differs in using `price` instead of `value` and using `hour` which is equal to `start` (`end` is implicit)

Format of raw_today:

```yaml
raw_today: 
- hour: '2023-01-02T00:00:00+01:00'
  price: 0.92
- hour: '2023-01-02T01:00:00+01:00'
  price: 0.862
- hour: '2023-01-02T02:00:00+01:00'
  price: 0.873
- hour: '2023-01-02T03:00:00+01:00'
  price: 0.792
- hour: '2023-01-02T04:00:00+01:00'
  price: 0.847
- hour: '2023-01-02T05:00:00+01:00'
  price: 1.039
- hour: '2023-01-02T06:00:00+01:00'
  price: 1.774
- hour: '2023-01-02T07:00:00+01:00'
  price: 2.114
- hour: '2023-01-02T08:00:00+01:00'
  price: 2.164
- hour: '2023-01-02T09:00:00+01:00'
  price: 2.174
- hour: '2023-01-02T10:00:00+01:00'
  price: 2.16
- hour: '2023-01-02T11:00:00+01:00'
  price: 2.139
- hour: '2023-01-02T12:00:00+01:00'
  price: 2.149
- hour: '2023-01-02T13:00:00+01:00'
  price: 2.143
- hour: '2023-01-02T14:00:00+01:00'
  price: 2.184
- hour: '2023-01-02T15:00:00+01:00'
  price: 2.251
- hour: '2023-01-02T16:00:00+01:00'
  price: 2.321
- hour: '2023-01-02T17:00:00+01:00'
  price: 3.663
- hour: '2023-01-02T18:00:00+01:00'
  price: 3.707
- hour: '2023-01-02T19:00:00+01:00'
  price: 3.611
- hour: '2023-01-02T20:00:00+01:00'
  price: 3.505
- hour: '2023-01-02T21:00:00+01:00'
  price: 2.124
- hour: '2023-01-02T22:00:00+01:00'
  price: 2.031
- hour: '2023-01-02T23:00:00+01:00'
  price: 1.904
```
