### ISSUE TITLE
Start/end time weird

### ISSUE THREAD

**Issue by BliXem1** [jonasbkarlsson/ev_smart_charging#94]
Hi,

First of all, many thanks for creating this!

I have a weird issue, apply price limit is on and the limit is above the 0,20 cents per kWh. But your script calculate this:

```
current_price: 0.2503792
EV SOC: '74'
EV target SOC: '80.0'
Charging is planned: true
**Charging start time: '2023-01-10T22:00:00+01:00'
Charging stop time: '2023-01-11T00:00:00+01:00'**
Charging number of hours: 2
raw_two_days:
  - start: '2023-01-09T00:00:00+01:00'
    end: '2023-01-09T01:00:00+01:00'
    value: 0.15950540000000002
  - start: '2023-01-09T01:00:00+01:00'
    end: '2023-01-09T02:00:00+01:00'
    value: 0.1481104
  - start: '2023-01-09T02:00:00+01:00'
    end: '2023-01-09T03:00:00+01:00'
    value: 0.14376440000000001
  - start: '2023-01-09T03:00:00+01:00'
    end: '2023-01-09T04:00:00+01:00'
    value: 0.1216422
  - start: '2023-01-09T04:00:00+01:00'
    end: '2023-01-09T05:00:00+01:00'
    value: 0.1116676
  - start: '2023-01-09T05:00:00+01:00'
    end: '2023-01-09T06:00:00+01:00'
    value: 0.126497
  - start: '2023-01-09T06:00:00+01:00'
    end: '2023-01-09T07:00:00+01:00'
    value: 0.171388
  - start: '2023-01-09T07:00:00+01:00'
    end: '2023-01-09T08:00:00+01:00'
    value: 0.2494676
  - start: '2023-01-09T08:00:00+01:00'
    end: '2023-01-09T09:00:00+01:00'
    value: 0.2706676
  - start: '2023-01-09T09:00:00+01:00'
    end: '2023-01-09T10:00:00+01:00'
    value: 0.26768899999999995
  - start: '2023-01-09T10:00:00+01:00'
    end: '2023-01-09T11:00:00+01:00'
    value: 0.2486408
  - start: '2023-01-09T11:00:00+01:00'
    end: '2023-01-09T12:00:00+01:00'
    value: 0.25029440000000003
  - start: '2023-01-09T12:00:00+01:00'
    end: '2023-01-09T13:00:00+01:00'
    value: 0.2278118
  - start: '2023-01-09T13:00:00+01:00'
    end: '2023-01-09T14:00:00+01:00'
    value: 0.2229676
  - start: '2023-01-09T14:00:00+01:00'
    end: '2023-01-09T15:00:00+01:00'
    value: 0.2251936
  - start: '2023-01-09T15:00:00+01:00'
    end: '2023-01-09T16:00:00+01:00'
    value: 0.2379772
  - start: '2023-01-09T16:00:00+01:00'
    end: '2023-01-09T17:00:00+01:00'
    value: 0.2508032
  - start: '2023-01-09T17:00:00+01:00'
    end: '2023-01-09T18:00:00+01:00'
    value: 0.2644242
  - start: '2023-01-09T18:00:00+01:00'
    end: '2023-01-09T19:00:00+01:00'
    value: 0.2729784
  - start: '2023-01-09T19:00:00+01:00'
    end: '2023-01-09T20:00:00+01:00'
    value: 0.2611276
  - start: '2023-01-09T20:00:00+01:00'
    end: '2023-01-09T21:00:00+01:00'
    value: 0.2503792
  - start: '2023-01-09T21:00:00+01:00'
    end: '2023-01-09T22:00:00+01:00'
    value: 0.22721819999999998
  - start: '2023-01-09T22:00:00+01:00'
    end: '2023-01-09T23:00:00+01:00'
    value: 0.2197876
  - start: '2023-01-09T23:00:00+01:00'
    end: '2023-01-10T00:00:00+01:00'
    value: 0.19467620000000002
  - start: '2023-01-10T00:00:00+01:00'
    end: '2023-01-10T01:00:00+01:00'
    value: 0.1922276
  - start: '2023-01-10T01:00:00+01:00'
    end: '2023-01-10T02:00:00+01:00'
    value: 0.182412
  - start: '2023-01-10T02:00:00+01:00'
    end: '2023-01-10T03:00:00+01:00'
    value: 0.1808008
  - start: '2023-01-10T03:00:00+01:00'
    end: '2023-01-10T04:00:00+01:00'
    value: 0.1755644
  - start: '2023-01-10T04:00:00+01:00'
    end: '2023-01-10T05:00:00+01:00'
    value: 0.1812036
  - start: '2023-01-10T05:00:00+01:00'
    end: '2023-01-10T06:00:00+01:00'
    value: 0.19498359999999998
  - start: '2023-01-10T06:00:00+01:00'
    end: '2023-01-10T07:00:00+01:00'
    value: 0.22651860000000001
  - start: '2023-01-10T07:00:00+01:00'
    end: '2023-01-10T08:00:00+01:00'
    value: 0.2452276
  - start: '2023-01-10T08:00:00+01:00'
    end: '2023-01-10T09:00:00+01:00'
    value: 0.2789144
  - start: '2023-01-10T09:00:00+01:00'
    end: '2023-01-10T10:00:00+01:00'
    value: 0.2757768
  - start: '2023-01-10T10:00:00+01:00'
    end: '2023-01-10T11:00:00+01:00'
    value: 0.2483334
  - start: '2023-01-10T11:00:00+01:00'
    end: '2023-01-10T12:00:00+01:00'
    value: 0.23632359999999997
  - start: '2023-01-10T12:00:00+01:00'
    end: '2023-01-10T13:00:00+01:00'
    value: 0.2303452
  - start: '2023-01-10T13:00:00+01:00'
    end: '2023-01-10T14:00:00+01:00'
    value: 0.230854
  - start: '2023-01-10T14:00:00+01:00'
    end: '2023-01-10T15:00:00+01:00'
    value: 0.23426719999999998
  - start: '2023-01-10T15:00:00+01:00'
    end: '2023-01-10T16:00:00+01:00'
    value: 0.2351364
  - start: '2023-01-10T16:00:00+01:00'
    end: '2023-01-10T17:00:00+01:00'
    value: 0.22980459999999997
  - start: '2023-01-10T17:00:00+01:00'
    end: '2023-01-10T18:00:00+01:00'
    value: 0.2366416
  - start: '2023-01-10T18:00:00+01:00'
    end: '2023-01-10T19:00:00+01:00'
    value: 0.233292
  - start: '2023-01-10T19:00:00+01:00'
    end: '2023-01-10T20:00:00+01:00'
    value: 0.2294018
  - start: '2023-01-10T20:00:00+01:00'
    end: '2023-01-10T21:00:00+01:00'
    value: 0.212198
  - start: '2023-01-10T21:00:00+01:00'
    end: '2023-01-10T22:00:00+01:00'
    value: 0.1878816
  - start: '2023-01-10T22:00:00+01:00'
    end: '2023-01-10T23:00:00+01:00'
    value: 0.16822920000000002
  - start: '2023-01-10T23:00:00+01:00'
    end: '2023-01-11T00:00:00+01:00'
    value: 0.1271648
charging_schedule:
  - start: '2023-01-09T00:00:00+01:00'
    end: '2023-01-09T01:00:00+01:00'
    value: 0
  - start: '2023-01-09T01:00:00+01:00'
    end: '2023-01-09T02:00:00+01:00'
    value: 0
  - start: '2023-01-09T02:00:00+01:00'
    end: '2023-01-09T03:00:00+01:00'
    value: 0
  - start: '2023-01-09T03:00:00+01:00'
    end: '2023-01-09T04:00:00+01:00'
    value: 0
  - start: '2023-01-09T04:00:00+01:00'
    end: '2023-01-09T05:00:00+01:00'
    value: 0
  - start: '2023-01-09T05:00:00+01:00'
    end: '2023-01-09T06:00:00+01:00'
    value: 0
  - start: '2023-01-09T06:00:00+01:00'
    end: '2023-01-09T07:00:00+01:00'
    value: 0
  - start: '2023-01-09T07:00:00+01:00'
    end: '2023-01-09T08:00:00+01:00'
    value: 0
  - start: '2023-01-09T08:00:00+01:00'
    end: '2023-01-09T09:00:00+01:00'
    value: 0
  - start: '2023-01-09T09:00:00+01:00'
    end: '2023-01-09T10:00:00+01:00'
    value: 0
  - start: '2023-01-09T10:00:00+01:00'
    end: '2023-01-09T11:00:00+01:00'
    value: 0
  - start: '2023-01-09T11:00:00+01:00'
    end: '2023-01-09T12:00:00+01:00'
    value: 0
  - start: '2023-01-09T12:00:00+01:00'
    end: '2023-01-09T13:00:00+01:00'
    value: 0
  - start: '2023-01-09T13:00:00+01:00'
    end: '2023-01-09T14:00:00+01:00'
    value: 0
  - start: '2023-01-09T14:00:00+01:00'
    end: '2023-01-09T15:00:00+01:00'
    value: 0
  - start: '2023-01-09T15:00:00+01:00'
    end: '2023-01-09T16:00:00+01:00'
    value: 0
  - start: '2023-01-09T16:00:00+01:00'
    end: '2023-01-09T17:00:00+01:00'
    value: 0
  - start: '2023-01-09T17:00:00+01:00'
    end: '2023-01-09T18:00:00+01:00'
    value: 0
  - start: '2023-01-09T18:00:00+01:00'
    end: '2023-01-09T19:00:00+01:00'
    value: 0
  - start: '2023-01-09T19:00:00+01:00'
    end: '2023-01-09T20:00:00+01:00'
    value: 0
  - start: '2023-01-09T20:00:00+01:00'
    end: '2023-01-09T21:00:00+01:00'
    value: 0
  - start: '2023-01-09T21:00:00+01:00'
    end: '2023-01-09T22:00:00+01:00'
    value: 0
  - start: '2023-01-09T22:00:00+01:00'
    end: '2023-01-09T23:00:00+01:00'
    value: 0
  - start: '2023-01-09T23:00:00+01:00'
    end: '2023-01-10T00:00:00+01:00'
    value: 0
  - start: '2023-01-10T00:00:00+01:00'
    end: '2023-01-10T01:00:00+01:00'
    value: 0
  - start: '2023-01-10T01:00:00+01:00'
    end: '2023-01-10T02:00:00+01:00'
    value: 0
  - start: '2023-01-10T02:00:00+01:00'
    end: '2023-01-10T03:00:00+01:00'
    value: 0
  - start: '2023-01-10T03:00:00+01:00'
    end: '2023-01-10T04:00:00+01:00'
    value: 0
  - start: '2023-01-10T04:00:00+01:00'
    end: '2023-01-10T05:00:00+01:00'
    value: 0
  - start: '2023-01-10T05:00:00+01:00'
    end: '2023-01-10T06:00:00+01:00'
    value: 0
  - start: '2023-01-10T06:00:00+01:00'
    end: '2023-01-10T07:00:00+01:00'
    value: 0
  - start: '2023-01-10T07:00:00+01:00'
    end: '2023-01-10T08:00:00+01:00'
    value: 0
  - start: '2023-01-10T08:00:00+01:00'
    end: '2023-01-10T09:00:00+01:00'
    value: 0
  - start: '2023-01-10T09:00:00+01:00'
    end: '2023-01-10T10:00:00+01:00'
    value: 0
  - start: '2023-01-10T10:00:00+01:00'
    end: '2023-01-10T11:00:00+01:00'
    value: 0
  - start: '2023-01-10T11:00:00+01:00'
    end: '2023-01-10T12:00:00+01:00'
    value: 0
  - start: '2023-01-10T12:00:00+01:00'
    end: '2023-01-10T13:00:00+01:00'
    value: 0
  - start: '2023-01-10T13:00:00+01:00'
    end: '2023-01-10T14:00:00+01:00'
    value: 0
  - start: '2023-01-10T14:00:00+01:00'
    end: '2023-01-10T15:00:00+01:00'
    value: 0
  - start: '2023-01-10T15:00:00+01:00'
    end: '2023-01-10T16:00:00+01:00'
    value: 0
  - start: '2023-01-10T16:00:00+01:00'
    end: '2023-01-10T17:00:00+01:00'
    value: 0
  - start: '2023-01-10T17:00:00+01:00'
    end: '2023-01-10T18:00:00+01:00'
    value: 0
  - start: '2023-01-10T18:00:00+01:00'
    end: '2023-01-10T19:00:00+01:00'
    value: 0
  - start: '2023-01-10T19:00:00+01:00'
    end: '2023-01-10T20:00:00+01:00'
    value: 0
  - start: '2023-01-10T20:00:00+01:00'
    end: '2023-01-10T21:00:00+01:00'
    value: 0
  - start: '2023-01-10T21:00:00+01:00'
    end: '2023-01-10T22:00:00+01:00'
    value: 0
  - start: '2023-01-10T22:00:00+01:00'
    end: '2023-01-10T23:00:00+01:00'
    value: 0.2091858
  - start: '2023-01-10T23:00:00+01:00'
    end: '2023-01-11T00:00:00+01:00'
    value: 0.2091858
icon: mdi:flash
friendly_name: EV Smart Charging Charging
```

Why does it takes tomorrow 22.00 hour and not earlier? For example, it can take 23.00 tonight (so this day and not tomorrow), the price is then 0,195.
